# Generated by Django 2.0.6 on 2019-01-29 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShipLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=30)),
                ('longitude', models.CharField(max_length=30)),
                ('ship_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ShipName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imo', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='shiplocation',
            name='imo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiplocation.ShipName'),
        ),
    ]
